import fs from 'node:fs';
import path from 'node:path';
import {argumentsFor, integerOption, isMain, onlyOption, requireFields} from '../cli.js';
import {counter, sortedEntries} from '../util.js';
import {ApiError, loadApiConfig, runApi} from './api.js';
import {runAgentApi} from './agent.js';
import {DEFAULT_AS_OF, Paths, defaultPaths, expand} from './config.js';
import {addExtraDoc} from './corpus.js';
import {pendingPackets, runIngest, writeOutputs} from './ingest.js';
import {DEFAULT_BUDGET, DEFAULT_MAX_CHARS, DEFAULT_PASTE_CHARS, makeBatches, prepare} from './packets.js';
export async function main(argv = process.argv.slice(2)): Promise<number> {
  const {values: v, command: c} = argumentsFor(argv, ['data-dir', 'work-dir', 'out-dir', 'extra-dir', 'as-of', 'max-chars', 'budget', 'paste-chars', 'only', 'model', 'base-url', 'env-file', 'rules-format', 'workers', 'file', 'jurisdiction', 'url', 'doc-id', 'source-type', 'retrieved'], ['once', 'dry-run', 'agent', 'all']);
  if (v.help) {console.log('npm run nav -- <prepare|bundle|api|ingest|status|add-doc> [参数]\n通用目录：--data-dir --work-dir --out-dir --extra-dir\nAPI：--agent --workers N --only D024 --once --dry-run --model --base-url --env-file\n准备：--as-of YYYY-MM-DD --max-chars N --budget N；bundle：--paste-chars N\n导入：--rules-format wrapped|list；status：--all\n补原文：--file --jurisdiction --url [--doc-id --source-type --retrieved]'); return 0;}
  if (!['prepare', 'bundle', 'api', 'ingest', 'status', 'add-doc'].includes(c)) throw new Error('请选择命令：prepare、bundle、api、ingest、status 或 add-doc');
  const defaults = defaultPaths(), p = new Paths(v['data-dir'] ? path.resolve(expand(v['data-dir'])) : defaults.data_dir, v['work-dir'] ? path.resolve(expand(v['work-dir'])) : defaults.work_dir, v['out-dir'] ? path.resolve(expand(v['out-dir'])) : defaults.out_dir, v['extra-dir'] ? path.resolve(expand(v['extra-dir'])) : defaults.extra_dir), only = onlyOption(v.only), format = v['rules-format'] || 'wrapped';
  if (!['wrapped', 'list'].includes(format)) throw new Error('rules-format 必须是 wrapped 或 list');
  if (c === 'prepare') {
    const index = prepare(p, v['as-of'] || DEFAULT_AS_OF, integerOption(v['max-chars'], DEFAULT_MAX_CHARS), integerOption(v.budget, DEFAULT_BUDGET), only), docs = Object.values<any>(index.docs), pk = Object.values<any>(index.packets), chars = pk.reduce((n, v) => n + v.chars, 0); console.log(`as of ${index.as_of} | ${docs.length} documents (${docs.filter(d => d.no_text).length} without text) | ${pk.length} packets | ${chars.toLocaleString('en-US')} characters`);
    const dropped = Object.entries<any>(index.docs).filter(([, d]) => d.dropped_blocks?.length); if (dropped.length) console.log('long documents trimmed (lowest-relevance blocks left out): ' + dropped.map(([id, d]) => `${id} (${d.dropped_blocks.length} blocks)`).join(', ')); console.log(`packets: ${p.packets_dir}\nprompt:  ${path.join(p.work_dir, 'PROMPT.md')}\ngaps:    ${path.join(p.work_dir, 'COVERAGE_GAPS.md')}\nnext: npm run nav -- bundle`); return 0;
  }
  if (c === 'bundle') {let pending = pendingPackets(runIngest(p)); if (only?.length) pending = Object.fromEntries(Object.entries(pending).filter(([pid]) => only.includes(pid.split('-')[0]) || only.includes(pid))); if (!Object.keys(pending).length) {console.log('Nothing pending: every packet has a complete, clean answer. Run: npm run nav -- ingest'); return 0;} const names = makeBatches(p, pending, integerOption(v['paste-chars'], DEFAULT_PASTE_CHARS)); console.log(`${Object.keys(pending).length} pending packet(s) -> ${names.length} paste file(s) in ${p.paste_dir}`); for (const name of names) console.log('  ' + name); console.log(`Hand a file to the model. Each one names its own answer file under ${p.inbox_dir} and, if the model can run\ncommands, tells it to run ingest itself. (Whole job in one go: give the model RUN_EXTRACTION.md.)`); return 0;}
  if (c === 'ingest') {const res = runIngest(p, v['as-of']), out = writeOutputs(p, res, format), c = res.counts; console.log(`answer files: ${c.files} | records: ${c.records_parsed} | accepted: ${c.accepted} | rejected (open): ${c.rejected} | rules: ${c.rules} | packets done: ${c.packets_done}/${c.packets_total}\nrules:  ${out.rules}\nreport: ${out.report}`); if (c.packets_done < c.packets_total) console.log('open packets remain: npm run nav -- bundle'); return 0;}
  if (c === 'status') {const res = runIngest(p); console.log(sortedEntries(counter(Object.values(res.states).map(s => s.state))).map(([k, v]) => `${k} ${v}`).join(', ') || 'no packets'); for (const [id, s] of Object.entries(res.states)) if (s.state !== 'done' || v.all) console.log(`  ${id.padEnd(10)} ${s.state.padEnd(11)} ${s.detail}`); return 0;}
  if (c === 'add-doc') {requireFields(v, ['file', 'jurisdiction', 'url']); const id = addExtraDoc(p, fs.readFileSync(expand(v.file), 'utf8'), v.jurisdiction, v.url, v['doc-id'] || '', v['source-type'] || 'official', v.retrieved || ''); console.log(`added ${id}; now run: npm run nav -- prepare --only ${id} && npm run nav -- bundle`); return 0;}
  try {if (!fs.existsSync(p.index_file)) throw new ApiError('尚未准备原文，请先运行 npm run nav -- prepare。'); const config = loadApiConfig(v['env-file'] ? expand(v['env-file']) : undefined, v.model, v['base-url'], !v['dry-run']), workers = integerOption(v.workers, 1); if (workers < 1) throw new Error('workers 必须是正整数'); const opts = {only, once: Boolean(v.once), dry_run: Boolean(v['dry-run']), rules_format: format}; return await (v.agent ? runAgentApi(p, config, {...opts, workers}) : runApi(p, config, opts));} catch (e) {console.error('API 流程停止：' + (e as Error).message); return 1;}
}
if (isMain(import.meta.url)) main().then(code => {process.exitCode = code;}).catch(e => {console.error(e.message); process.exitCode = 1;});
