import fs from 'node:fs';
import path from 'node:path';
import type {Data} from '../types.js';
import {argumentsFor, isMain} from '../cli.js';
import {counter, equal, hashFile, pyStr, readJson, repr, sortedEntries, walk, writeJson, writeText} from '../util.js';
import {ChangeTracker} from '../changes/engine.js';
import {CensusResolver, loadAddresses} from './addresses.js';
import {DEFAULT_DATE, DISCLAIMER, ROOT, pack} from './common.js';
import {LookupEngine, loadRules, stateOf} from './engine.js';
import {render} from './review.js';
export function requestsReport(engine: LookupEngine, audit: Data, changesAudit: Data, supplements?: Data): string {
  const grouped = new Map<string, Set<string>>(), explanations: Record<string, string> = {};
  for (const [id, address] of Object.entries<Data>(audit.addresses)) for (const t of address.rules) if (t.result === 'unknown') for (const m of t.missing_facts || []) {const key = JSON.stringify([t.team_rule_id, m.field]); if (!grouped.has(key)) grouped.set(key, new Set()); grouped.get(key)!.add(id); explanations[key] = m.explanation;}
  const lines = ['# 第二、三阶段对事实的需求', '', '本文件由查询结果生成，不修改第一阶段的程序。', '', '缺规则或缺适用条件时，请补原文和可判断的事实；缺房东、入住证、租约等地址事实时，应补公开地址数据，不能由第一阶段猜测。', '', '## 缺失的变更规则', ''];
  for (const [id, c] of Object.entries<Data>(changesAudit.tests)) if (c.missing_rules.length) lines.push(`- ${id}：${c.missing_rules.join('、')}。需补原文、引用、通过状态、生效日期、适用条件和州/市关系。`);
  if (fs.existsSync(path.join(ROOT, 'corpus_extra/text/D034.txt'))) lines.push('- Hoboken 的 D034 原文已经出现在 corpus_extra/text/D034.txt；若规则对照仍为空，需要第一阶段完成提取，而不是继续报原文不存在。第二、三阶段不会手工编造这条规则。');
  lines.push('', '## 每条规则缺少的判断事实', ''); for (const [key, aids] of [...grouped.entries()].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)) {const [rid, field] = JSON.parse(key), rule = engine.by_id[rid]; lines.push(`### ${rid} — ${rule.jurisdiction} — ${rule.citation}`, `- 字段：\`${field}\`；缺口：${explanations[key]}。`, `- 因此不确定的地址（${aids.size}个）：${[...aids].sort().join(', ')}`, '');}
  lines.push('## 需要第一阶段核对的输入条件', ''); for (const r of engine.rules) {const a = r.applicability || {}; if (r.exemptions && !['owner_dependent', 'other', 'built_on_or_before', 'built_after', 'exempt_if_newer_than_years', 'covered_if_newer_than_years', 'min_units', 'max_units', 'deferred', 'alternatives'].some(k => Array.isArray(a[k]) ? a[k].length : a[k])) {const ids = sortedEntries(engine.addresses).filter(([, a]) => a.state === stateOf(r) && (r.level === 'state' || a.legal_city === r.jurisdiction)).map(([id]) => id); lines.push(`- ${r.team_rule_id}（${r.citation}）：有豁免文字，但没有对应结构条件。请确认是建筑覆盖条件还是行为/义务条件，不要把豁免条件反写成适用条件。可能相关地址：${ids.join(', ') || '样本暂无'}。原文摘录：${r.exemptions}`);}}
  if (supplements) {lines.push('', '## 人工补充条目（lookup/coverage_facts.json）的核对', '', '- 没有命中任何规则的条目（规则改名或合并后，这条补充已经不起作用，需要改匹配条件或删除）：' + (supplements.unused?.join(', ') || '无')); for (const d of supplements.differs || []) lines.push(`- ${d.supplement} 覆盖了提取结果：${d.rule}（${d.citation}）的 \`${d.field}\`，提取是 ${repr(d.extracted)}，补充是 ${repr(d.supplement_value)}`); if (!supplements.differs?.length) lines.push('- 没有补充条目改写提取出的值。');}
  lines.push('', '## 第一阶段重新生成的情况', ''); const file = path.join(ROOT, 'work/rejected.jsonl'); if (fs.existsSync(file)) {const rows = fs.readFileSync(file, 'utf8').split('\n').filter(l => l.trim()).map(l => JSON.parse(l)); lines.push(`- 当前重新生成有${rows.filter(r => r.open).length}条尚未通过第一阶段检查的记录。应在第一阶段核对原文，不由第二、三阶段绕过其检查。详见 work/rejected.jsonl 与 work/report.md。`);} return [...lines, '', DISCLAIMER, ''].join('\n');
}
export async function main(argv = process.argv.slice(2)): Promise<number> {
  const {values: v, command: c} = argumentsFor(argv, ['as-of', 'address-id', 'addresses', 'resolved', 'rules', 'output-dir', 'work-dir', 'cache-dir', 'geocode-mode', 'date-overrides'], ['offline', 'refresh']);
  if (v.help) {console.log('npm run lookup -- <resolve|build|lookup|changes|review> [参数]\n--as-of YYYY-MM-DD --address-id A0001 --offline --refresh --geocode-mode single|batch\n--addresses --resolved --rules --output-dir --work-dir --cache-dir --date-overrides'); return 0;}
  if (!['resolve', 'build', 'lookup', 'changes', 'review'].includes(c)) throw new Error('请选择命令：resolve、build、lookup、changes 或 review');
  const addressesFile = v.addresses || path.join(pack(), 'data/sample_addresses.csv'), resolvedFile = v.resolved || path.join(ROOT, 'work/addresses_resolved.json'), rulesFile = v.rules || path.join(ROOT, 'work/rules_enriched.json'), outDir = v['output-dir'] || path.join(ROOT, 'outputs'), workDir = v['work-dir'] || path.join(ROOT, 'work'), asOf = v['as-of'] || DEFAULT_DATE;
  if (c === 'resolve') {let previous = -1; const resolved = await new CensusResolver(v['cache-dir'] || path.join(ROOT, 'work/geocode_cache'), Boolean(v.offline), Boolean(v.refresh), undefined, undefined, v['geocode-mode'] || 'single').resolve(loadAddresses(addressesFile), undefined, (done, total) => {if (Math.floor(done / 25) !== previous || done === total) {console.log(`Census 地址和城市边界查询 ${done}/${total}`); previous = Math.floor(done / 25);}}); writeJson(resolvedFile, resolved); console.log(`已保存${Object.keys(resolved).length}个地址；解析方式：${repr(counter(Object.values<Data>(resolved).map(a => a.resolved_by)))}。${DISCLAIMER}`); return 0;}
  const addresses = readJson(resolvedFile), raw = loadAddresses(addressesFile); if (!equal(Object.keys(raw).sort(), Object.keys(addresses).sort())) throw new Error('已解析地址与地址表编号不一致，请重新 resolve'); for (const [id, r] of Object.entries<Data>(raw)) if (Object.entries(r).some(([k, value]) => !equal(addresses[id][k] ?? null, value))) throw new Error(`${id}的地址或建筑事实已改变，请重新 resolve，避免使用旧解析资料`);
  const report: Data = {}, engine = new LookupEngine(loadRules(rulesFile, undefined, report), addresses); if (report.unused?.length) console.log('注意：补充条目没有命中任何规则：' + report.unused.join(', '));
  if (c === 'review') {const target = path.join(workDir, 'conditions_review.md'); writeText(target, render(engine, asOf)); console.log('条件核对表：' + target); return 0;}
  if (c === 'lookup') {if (!v['address-id']) throw new Error('单地址查询需要 --address-id'); console.log(JSON.stringify({as_of: asOf, address_id: v['address-id'], results: engine.lookup(v['address-id'], asOf), disclaimer: DISCLAIMER}, null, 2)); return 0;}
  const overrides = v['date-overrides'] ? readJson(v['date-overrides']) : undefined, [changes, changeAudit] = new ChangeTracker(engine).run(overrides);
  if (c === 'changes') {writeJson(path.join(outDir, 'changes.json'), changes); writeJson(path.join(workDir, 'changes_audit.json'), changeAudit);}
  else {
    const [lookups, audit] = engine.all(asOf), rules = engine.exportedRules(asOf, lookups); writeJson(path.join(outDir, 'rules.json'), {rules}); writeJson(path.join(outDir, 'lookups.json'), lookups); writeJson(path.join(outDir, 'changes.json'), changes); writeJson(path.join(workDir, 'lookup_audit.json'), audit); writeJson(path.join(workDir, 'changes_audit.json'), changeAudit); writeText(path.join(workDir, 'stage1_requests.md'), requestsReport(engine, audit, changeAudit, report));
    const inputs = [addressesFile, resolvedFile, rulesFile, ...['precedence.json', 'coverage_facts.json', 'postal_cities.json'].map(f => path.join(ROOT, 'lookup', f)), path.join(ROOT, 'changes/test_rule_map.json'), path.join(pack(), 'dev/change_tests.json'), ...walk(path.join(ROOT, 'src')).filter(f => f.endsWith('.ts') && !f.includes('/tests/')), path.join(ROOT, 'package-lock.json'), path.join(ROOT, 'tsconfig.json'), ...[path.join(ROOT, 'work/rejected.jsonl'), path.join(ROOT, 'corpus_extra/text/D034.txt')].filter(f => fs.existsSync(f))]; if (v['date-overrides']) inputs.push(v['date-overrides']);
    const manifest = {as_of: asOf, disclaimer: DISCLAIMER, inputs: Object.fromEntries(inputs.map(p => {const abs = path.resolve(p), rel = path.relative(path.dirname(ROOT), abs); return [rel.startsWith('..' + path.sep) ? abs : rel, hashFile(p)];})), outputs: Object.fromEntries(['rules.json', 'lookups.json', 'changes.json'].map(f => [f, hashFile(path.join(outDir, f))])), audit_outputs: Object.fromEntries(['lookup_audit.json', 'changes_audit.json', 'stage1_requests.md'].map(f => [f, hashFile(path.join(workDir, f))])), address_count: Object.keys(addresses).length, rule_count: rules.length, geocode_methods: counter(Object.values<Data>(addresses).map(a => a.resolved_by)), results: counter(Object.values<Data[]>(lookups.lookups).flat().map(r => r.result))}; writeJson(path.join(workDir, 'stage23_audit.json'), manifest); console.log(`已导出${Object.keys(addresses).length}个地址、${rules.length}条规则及${Object.keys(changes).length}道变更题；输入和输出指纹在 stage23_audit.json`);
  }
  for (const [id, a] of Object.entries<Data>(changes)) console.log(`${id}：受影响${a.affected_address_ids.length}个，需复核${a.conflict_flag_address_ids.length}个`); console.log(DISCLAIMER); return 0;
}
if (isMain(import.meta.url)) main().then(code => {process.exitCode = code;}).catch(e => {console.error('第二、三阶段停止：' + e.message); process.exitCode = 1;});
