import type {Data} from '../types.js';
import {cmp, pyStr, slice, sortedEntries} from '../util.js';
import {DEFAULT_DATE} from './common.js';
import {LookupEngine} from './engine.js';
export function describeConditions(rule: Data): string[] {
  const a = rule.applicability || {}, parts: string[] = [], labels: [string, string][] = [['built_on_or_before', 'covered if built on or before %s'], ['built_before', 'covered if built before %s'], ['built_after', 'covered if built after %s'], ['built_on_or_after', 'covered if built on or after %s'], ['min_units', 'at least %s units'], ['max_units', 'at most %s units'], ['exempt_if_newer_than_years', 'exempt if newer than %s years'], ['covered_if_newer_than_years', 'covered only if built within the last %s years'], ['owner_exempt_if_units_at_most', 'owner exemption up to %s units']];
  for (const [k, t] of labels) if (a[k] != null) parts.push(t.replace('%s', pyStr(a[k])));
  if (a.owner_dependent && a.owner_exempt_if_units_at_most == null) parts.push('owner-dependent, no size limit (unknown for every address)');
  for (const item of a.alternatives || []) parts.push(`covered if ${Object.entries(item.flats).filter(([k]) => k !== 'date_basis').map(([k, v]) => `${k}=${pyStr(v)}`).join(', ')}, or also (open question outside the limit): ${item.also}`);
  if (a.date_basis && ['built_on_or_before', 'built_before', 'built_after', 'built_on_or_after', 'exempt_if_newer_than_years', 'covered_if_newer_than_years'].some(k => a[k])) parts.push('date basis: ' + a.date_basis);
  for (const item of a.deferred || []) parts.push('exemption only if the owner filed (open question inside its reach): ' + item.note);
  if (a.other) parts.push('UNRESOLVED: ' + a.other); if (a.program_notes?.length) parts.push('note, does not change the answer (kinds of housing the data cannot show): ' + a.program_notes.join('; ')); if (a.per_tenancy) parts.push('note: ' + a.per_tenancy); return parts;
}
export function collect(engine: LookupEngine, asOf = DEFAULT_DATE): Record<string, Record<string, number>> {
  const stats = Object.fromEntries(engine.rules.map(r => [r.team_rule_id, {} as Record<string, number>])); for (const id of Object.keys(engine.addresses).sort()) {const [results, audit] = engine.evaluate(id, asOf), final = Object.fromEntries(results.map(r => [r.team_rule_id, r.result])); for (const t of audit.rules) {const rid = t.team_rule_id; if (t.stopped_at_step === 1 && !final[rid]) continue; const key = final[rid] || 'omitted: ' + (t.stopped_at_step === 2 ? 'failed measure' : t.stopped_at_step === 6 ? 'a condition excludes it' : t.stopped_at_step === 4 ? 'outside its valid period' : 'other'); stats[rid][key] = (stats[rid][key] || 0) + 1;}} return stats;
}
export function render(engine: LookupEngine, asOf = DEFAULT_DATE): string {
  const stats = collect(engine, asOf), out = [`# 条件核对表（第一阶段提取的条件对 ${Object.keys(engine.addresses).length} 个地址的影响）`, '', '条件由模型从原文读出，请抽查。最贵的错误是**误判豁免**：规则会在本该适用的地址上悄悄消失。', `下面先列需要优先看的规则，再列全部规则。查询日期 ${asOf}。`, ''];
  const rows = [...engine.rules].sort((a, b) => cmp([a.jurisdiction, a.category, a.citation], [b.jurisdiction, b.category, b.citation])).map(rule => {const rid = rule.team_rule_id, c = stats[rid], scope = Object.values(c).reduce((a, b) => a + b, 0), omitted = Object.entries(c).filter(([k]) => k.startsWith('omitted: a condition')).reduce((n, [, v]) => n + v, 0), why: string[] = []; if (omitted) why.push(`条件使它在 ${omitted} 个地址上消失`); if (scope && c.unknown === scope) why.push(`所有 ${scope} 个地址都是不确定`); if (rule.applicability?.built_on_or_before == null && ['built_before', 'built_after', 'built_on_or_after'].some(k => rule.applicability?.[k])) why.push('只有单侧日期条件，请核对方向'); return {rid, rule, c, scope, why};});
  const block = ({rid, rule, c, scope, why}: typeof rows[number]): string[] => {const lines = [`### ${rid} — ${rule.jurisdiction} — ${rule.category} — ${rule.citation}`, `- 状态：${pyStr(rule.lifecycle)}；生效日期：${rule.effective_date || '原文未载明'}；有效期至：${rule.valid_through || '—'}`, '- 条件：' + (describeConditions(rule).join('；') || '无'), `- 地址结果（共 ${scope} 个在范围内）：${sortedEntries(c).map(([k, v]) => `${k} ${v}`).join('，') || '—'}`]; if (why.length) lines.push('- **注意：' + why.join('；') + '**'); for (const s of rule.coverage_sources || []) lines.push(`- 手写补充条目 \`${s.id}\`（不是模型提取）：${slice(pyStr(s.basis).replace(/\s+/g, ' '), 0, 300)}；来源：${s.source}`); for (const q of rule.applicability?.coverage_quotes || []) lines.push('- 原文：> ' + slice(q.replace(/\s+/g, ' '), 0, 420)); for (const r of rule.relations || []) lines.push(`- 关系 \`${r.type}\`：> ${slice(r.quote.replace(/\s+/g, ' '), 0, 300)}`); lines.push(''); return lines;};
  const flagged = rows.filter(r => r.why.length); out.push(`## 优先核对（${flagged.length} 条）`, '', ...flagged.flatMap(block), `## 全部规则（${rows.length} 条）`, '', ...rows.flatMap(block)); return out.join('\n') + '\n';
}
